import os
import uuid
import gradio as gr
from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage, AIMessage

# Import your existing MVP architecture
from graph import compile_app
from main import get_initial_state, OPENSHIFT_MODEL_URL

# --- 1. INITIALIZE MODEL & GRAPH ---
os.environ["OPENAI_API_BASE"] = OPENSHIFT_MODEL_URL

llm = ChatOpenAI(
    model="sarhachat",
    temperature=0.2,
    max_tokens=1500,
)
app = compile_app(llm)

# --- 2. GRADIO INTERACTION LOGIC ---
def start_session():
    """Boots up the graph immediately on page load to fetch the first greeting."""
    thread_id = str(uuid.uuid4())
    config = {"configurable": {"thread_id": thread_id}}
    
    # Seed initial state
    app.invoke(get_initial_state(), config=config)
    
    # Fetch the greeting generated by Stage 1
    current_state = app.get_state(config).values
    messages = current_state.get("messages", [])
    latest_ai_msg = messages[-1].content if messages else "Hello! I am SARHAchat."
    
    history = [{"role": "assistant", "content": latest_ai_msg}]
    display_state = {k: v for k, v in current_state.items() if k not in ["messages", "rag_context"]}
    rag_text = current_state.get("rag_context", "Awaiting Stage 4 RAG retrieval...")
    
    return history, display_state, rag_text, thread_id

def interact_with_agent(user_message, history, thread_id):
    config = {"configurable": {"thread_id": thread_id}}
    
    # Add user message to history instantly for UX
    history.append({"role": "user", "content": user_message})
    yield "", history, gr.update(), gr.update(), thread_id # Yielding UI update instantly
    
    # Pass user message into LangGraph
    app.invoke({"messages": [HumanMessage(content=user_message)]}, config=config)
    
    # Fetch the newly updated state
    current_state = app.get_state(config).values
    messages = current_state.get("messages", [])
    
    # Extract the latest AI response
    latest_ai_msg = messages[-1].content if messages else "..."
    history.append({"role": "assistant", "content": latest_ai_msg})
    
    # Prepare State and RAG display
    raw_state = {k: v for k, v in current_state.items() if k not in ["messages", "rag_context"]}
    
    display_state = {}
    for key, value in raw_state.items():
        # ONLY add it to the UI if it has real data (ignore None, False, empty lists, empty strings)
        if value not in [None, "", []]:
            # Clean up the snake_case keys for a prettier dashboard (e.g., 'blood_clots' -> 'Blood Clots')
            clean_key = key.replace("_", " ").title()
            display_state[clean_key] = value
    rag_text = current_state.get("rag_context", "Awaiting Stage 4 RAG retrieval...")
    
    yield "", history, display_state, rag_text, thread_id

# --- 3. BUILD THE GRADIO UI ---
with gr.Blocks(title="SARHAchat Contraceptive Triage") as demo:
    gr.Markdown("# 🏥 SARHAchat: The Sexual and Reproductive Health Assistant")
    gr.Markdown("Left: Fine-Tuned LLM Chatbot | Right: Deterministic LangGraph State Tracking & RAG")
    
    thread_id_state = gr.State("")
    
    with gr.Row():
        # LEFT PANE: Chat Interface
        with gr.Column(scale=2):
            chatbot = gr.Chatbot(label="Patient Interaction", height=600)
            user_input = gr.Textbox(
                label="Message SARHAchat", 
                placeholder="Type your message and press Enter..."
            )
            clear_btn = gr.Button("🔄 Reset Clinical Session")
            
        # RIGHT PANE: Live State Dashboard & RAG
        with gr.Column(scale=1):
            state_display = gr.JSON(label="🧠 Live LangGraph Memory State")
            with gr.Accordion("📚 Extracted CDC MEC Guidelines (RAG)", open=False):
                rag_display = gr.Markdown("Awaiting Stage 4 RAG retrieval...")

    # Wire up the interactions
    demo.load(
        start_session, 
        inputs=None, 
        outputs=[chatbot, state_display, rag_display, thread_id_state]
    )
    
    user_input.submit(
        interact_with_agent, 
        inputs=[user_input, chatbot, thread_id_state], 
        outputs=[user_input, chatbot, state_display, rag_display, thread_id_state]
    )
    
    clear_btn.click(
        start_session, # Resets exactly like a new page load
        inputs=None, 
        outputs=[chatbot, state_display, rag_display, thread_id_state]
    )

# --- 4. LAUNCH ---
demo.launch(server_name="0.0.0.0", server_port=8080, share=True)